# Generated by Django 5.1.3 on 2024-11-16 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ElectionModel',
            fields=[
                ('election_id', models.AutoField(primary_key=True, serialize=False)),
                ('election_title', models.CharField(max_length=100)),
                ('election_description', models.TextField(blank=True, null=True)),
                ('election_cutoff', models.IntegerField(blank=True, null=True)),
                ('election_reward', models.TextField(blank=True, null=True)),
                ('election_eligibility', models.JSONField(blank=True, choices=[('DECLARED', 'Declared'), ('NOMINATION', 'Nomination'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='DECLARED', null=True)),
                ('nomination_start_date', models.DateTimeField()),
                ('nomination_end_date', models.DateTimeField()),
                ('voting_start_date', models.DateTimeField()),
                ('voting_end_date', models.DateTimeField()),
                ('created_by_name', models.CharField(max_length=50)),
                ('created_by_empid', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'election',
            },
        ),
        migrations.CreateModel(
            name='EmpVotingModel',
            fields=[
                ('emp_vote_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_role', models.CharField(max_length=250)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_process.electionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NominationsModel',
            fields=[
                ('nomination_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_role', models.CharField(blank=True, max_length=250, null=True)),
                ('appeal', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_process.electionmodel')),
            ],
        ),
        migrations.CreateModel(
            name='NomineeVoteCountModel',
            fields=[
                ('nominee_vote_count_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField()),
                ('total_votes', models.IntegerField(default=0)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_process.electionmodel')),
                ('nomination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election_process.nominationsmodel')),
            ],
        ),
    ]
