# Generated by Django 5.1.3 on 2024-11-16 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='empvotingmodel',
            table='emp_voting',
        ),
        migrations.AlterModelTable(
            name='nominationsmodel',
            table='nominations',
        ),
        migrations.AlterModelTable(
            name='nomineevotecountmodel',
            table='nomination_vote_count',
        ),
    ]
