# Generated by Django 5.1.3 on 2024-11-16 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0002_alter_empvotingmodel_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionmodel',
            name='election_status',
            field=models.CharField(blank=True, choices=[('DECLARED', 'Declared'), ('NOMINATION', 'Nomination'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='DECLARED', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='electionmodel',
            name='election_eligibility',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
