# Generated by Django 5.1.3 on 2024-11-20 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0003_electionmodel_election_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionmodel',
            name='election_status',
            field=models.CharField(blank=True, choices=[('DECLARED', 'Declared'), ('NOMINATION', 'Nominations'), ('LIVE', 'Live'), ('COMPLETED', 'Completed'), ('CLOSED', 'Closed')], default='DECLARED', max_length=100, null=True),
        ),
    ]
