# Generated by Django 5.1.3 on 2024-11-23 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0004_alter_electionmodel_election_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionmodel',
            name='election_status',
            field=models.CharField(blank=True, choices=[('Declared', 'Declared'), ('Nominations', 'Nominations'), ('Live', 'Live'), ('Completed', 'Completed'), ('Closed', 'Closed')], default='Declared', max_length=100, null=True),
        ),
    ]
