# Generated by Django 5.1.3 on 2024-11-30 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0005_alter_electionmodel_election_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='electionmodel',
            name='created_by_empid',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electionmodel',
            name='created_by_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='electionmodel',
            name='nomination_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electionmodel',
            name='nomination_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electionmodel',
            name='voting_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='electionmodel',
            name='voting_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
