# Generated by Django 5.1.3 on 2024-12-09 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0007_electionmodel_results_published_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nomineevotecountmodel',
            name='nomination',
        ),
    ]
