# Generated by Django 5.1.3 on 2024-12-12 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0008_remove_nomineevotecountmodel_nomination'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionmodel',
            name='election_status',
        ),
    ]
