# Generated by Django 5.1.3 on 2024-12-15 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0009_remove_electionmodel_election_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electionmodel',
            name='election_cutoff',
        ),
        migrations.RemoveField(
            model_name='empvotingmodel',
            name='emp_role',
        ),
        migrations.RemoveField(
            model_name='nominationsmodel',
            name='emp_role',
        ),
        migrations.AddField(
            model_name='nomineevotecountmodel',
            name='nomination',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='election_process.nominationsmodel'),
            preserve_default=False,
        ),
    ]
