# Generated by Django 5.1.3 on 2024-12-16 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0010_remove_electionmodel_election_cutoff_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleModel',
            fields=[
                ('role_id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.RenameField(
            model_name='empvotingmodel',
            old_name='emp_id',
            new_name='rckr_emp_id',
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('emp_id', models.IntegerField(unique=True)),
                ('emp_name', models.CharField(max_length=100)),
                ('emp_email', models.EmailField(max_length=254, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('role_id', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='election_process.rolemodel')),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
