# Generated by Django 5.1.3 on 2024-12-16 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0011_rolemodel_rename_emp_id_empvotingmodel_rckr_emp_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nominationsmodel',
            old_name='emp_id',
            new_name='rckr_emp_id',
        ),
    ]
