# Generated by Django 5.1.3 on 2024-12-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0012_rename_emp_id_nominationsmodel_rckr_emp_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='nominationsmodel',
            name='emp_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
