# Generated by Django 5.1.3 on 2024-12-16 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0013_nominationsmodel_emp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empvotingmodel',
            old_name='rckr_emp_id',
            new_name='emp_id',
        ),
    ]
