# Generated by Django 5.1.3 on 2024-12-17 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0014_rename_rckr_emp_id_empvotingmodel_emp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermodel',
            name='role_id',
        ),
        migrations.DeleteModel(
            name='RoleModel',
        ),
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
