# Generated by Django 5.1.3 on 2024-12-18 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0015_remove_usermodel_role_id_delete_rolemodel_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empvotingmodel',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='nominationsmodel',
            name='emp_id',
        ),
        migrations.RemoveField(
            model_name='nomineevotecountmodel',
            name='emp_id',
        ),
        migrations.AddField(
            model_name='empvotingmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nominationsmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='nomineevotecountmodel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
