# Generated by Django 5.1.3 on 2024-12-18 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0018_empusermodel_delete_userempmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empusermodel',
            name='ext_emp_id',
            field=models.IntegerField(unique=True),
        ),
    ]
