# Generated by Django 5.1.3 on 2024-12-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0020_rename_emp_name_empvotingmodel_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='electionmodel',
            name='election_total_votes',
            field=models.IntegerField(default=40),
            preserve_default=False,
        ),
    ]
