# Generated by Django 5.1.3 on 2025-01-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election_process', '0021_electionmodel_election_total_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empvotingmodel',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='nominationsmodel',
            name='user_name',
        ),
        migrations.RemoveField(
            model_name='nomineevotecountmodel',
            name='election',
        ),
        migrations.RemoveField(
            model_name='nomineevotecountmodel',
            name='user',
        ),
    ]
